### login
POST http://localhost:8080/login
Accept: application/json
Content-Type: application/json

{
  "login": "test34et5",
  "password": "NewAndTotallyUniquePassword"
}

### create new user
POST http://localhost:8080/create-user
Accept: application/json
Content-Type: application/json

{
  "login": "test4",
  "password":  "test",
  "email": "test",
  "name":  "test",
  "surname": "test"
}

### get postboxes of logged in user
POST http://localhost:8080/PostBoxes
Accept: application/json
Content-Type: application/json

{
  "username": "test3"
}


### create new postbox for user with given id
POST http://localhost:8080/put/PostBoxes/5
Accept: application/json
Content-Type: application/json

{
  "name": "test",
  "address":  "test",
  "notes": "test"
}

### new lid-state
POST http://localhost:8080/update-lidState
Accept: application/json
Content-Type: application/json

{
  "postboxId": 3,
  "timestamp": [2024,5,25,2,7,52,942372300],
  "isOpen": true
}

### new door-state
POST http://localhost:8080/update-doorState
Accept: application/json
Content-Type: application/json

{
  "postboxId": 1,
  "timestamp": [2024,5,25,2,7,52,942372300],
  "isOpen": true
}

### new battery-state
POST http://localhost:8080/update-batteryState
Accept: application/json
Content-Type: application/json

{
  "postboxId": 1,
  "timestamp": [2024,5,25,2,7,52,942372300],
  "charge": 50
}

### new weight-state
POST http://localhost:8080/update-weightState
Accept: application/json
Content-Type: application/json

{
  "postboxId": 1,
  "timestamp": [2024,5,25,2,7,52,942372300],
  "weight": 10.32
}

### change login
POST http://localhost:8080/change-login
Accept: application/json
Content-Type: application/json

{
  "username": "mashina.katherina@gmail.com",
  "newLogin": "test"
}

### change password
POST http://localhost:8080/change-password
Accept: application/json
Content-Type: application/json

{
  "username": "test34et5",
  "newPassword": "NewAndTotallyUniquePassword"
}
